name = "SymbolicTensors"
uuid = "55c8b40c-cbfa-4141-803e-4831c9841971"
version = "1.0.0"
authors = ["THelpin <thomas1.helpin@gmail.com> and contributors"]

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"

[weakdeps]
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"

[extensions]
SymbolicTensorsSymbolicsExt = "Symbolics"

[compat]
BenchmarkTools = "1.8.0"
Symbolics = "5, 6, 7.35"
julia = "1.10"

[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
bench = ["BenchmarkTools"]
test = ["Test", "Symbolics"]
